

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import newpackage.Beszállító;
import newpackage.DbKapcsolat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kicsi
 */
public class BeszallitoHozzaad extends javax.swing.JPanel {

    private DbKapcsolat db;

    public BeszallitoHozzaad() {
        initComponents();
        radioGombok.add(hozzaadRadioGomb);
        radioGombok.add(modositRadioGomb);
        radioGombok.add(torolRadioGomb);
        db = frame.getDbKapcsolat();

        nev.setEditable(false);
        nev.setBackground(Color.LIGHT_GRAY);
        telephely.setEditable(false);
        telephely.setBackground(Color.LIGHT_GRAY);
        telefonszam.setEditable(false);
        telefonszam.setBackground(Color.LIGHT_GRAY);
        email.setEditable(false);
        email.setBackground(Color.LIGHT_GRAY);
        adoszam.setEditable(false);
        adoszam.setBackground(Color.LIGHT_GRAY);
        beszallitoLista.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        radioGombok = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        beszallitoLista = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nev = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telephely = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        telefonszam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        adoszam = new javax.swing.JTextField();
        hozzaadGomb = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        hozzaadRadioGomb = new javax.swing.JRadioButton();
        modositRadioGomb = new javax.swing.JRadioButton();
        torolRadioGomb = new javax.swing.JRadioButton();
        keresGomb = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Beszállító:");

        beszallitoLista.setEditable(true);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Név:");

        nev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telephely:");

        telephely.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefonszám:");

        telefonszam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("E-mail cím:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Adószám:");

        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        adoszam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        hozzaadGomb.setBackground(new java.awt.Color(0, 102, 153));
        hozzaadGomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick-512 (1).png"))); // NOI18N
        hozzaadGomb.setBorder(null);
        hozzaadGomb.setBorderPainted(false);
        hozzaadGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadGombActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Beszállító műveletek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        hozzaadRadioGomb.setBackground(new java.awt.Color(0, 102, 153));
        hozzaadRadioGomb.setForeground(new java.awt.Color(255, 255, 255));
        hozzaadRadioGomb.setText("Új beszállító hozzáadása");
        hozzaadRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadRadioGombActionPerformed(evt);
            }
        });

        modositRadioGomb.setBackground(new java.awt.Color(0, 102, 153));
        modositRadioGomb.setForeground(new java.awt.Color(255, 255, 255));
        modositRadioGomb.setText("Beszállító adatmódosítás");
        modositRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modositRadioGombActionPerformed(evt);
            }
        });

        torolRadioGomb.setBackground(new java.awt.Color(0, 102, 153));
        torolRadioGomb.setForeground(new java.awt.Color(255, 255, 255));
        torolRadioGomb.setText("Beszállító törlés");
        torolRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torolRadioGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(hozzaadRadioGomb)
                .addGap(55, 55, 55)
                .addComponent(modositRadioGomb)
                .addGap(49, 49, 49)
                .addComponent(torolRadioGomb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modositRadioGomb)
                    .addComponent(torolRadioGomb)
                    .addComponent(hozzaadRadioGomb))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        keresGomb.setText("jButton1");
        keresGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keresGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beszallitoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keresGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telephely)
                    .addComponent(adoszam, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(telefonszam, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hozzaadGomb))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(beszallitoLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(keresGomb))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(telephely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(telefonszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(adoszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hozzaadGomb)))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hozzaadGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadGombActionPerformed

        try {
            String nev_ = nev.getText();
            String telephely_ = telephely.getText();
            String telefonszam_ = telefonszam.getText();
            String email_ = email.getText();
            String adoszam_ = adoszam.getText();
            int cegId_=0;
            try{
            cegId_=((Beszállító) beszallitoLista.getSelectedItem()).getCegId();
            
            }catch(Exception e){
            
            }
            if (nev_.equals("") || telephely_.equals("") || email_.equals("")) {
                JOptionPane.showMessageDialog(null, "A név, telephely, e-mail cím megadása kötelező!");
                return;
            }
            if (!(email_.contains("@") && email_.contains("."))) {
                JOptionPane.showMessageDialog(null, "Hibás e-mail cím!");
                return;
            }

            Beszállító beszallito = new Beszállító(cegId_,nev_, telephely_, telefonszam_, email_, adoszam_);
            
            if (hozzaadRadioGomb.isSelected()) {
                db.ujBeszallito(beszallito);
            }
            if (modositRadioGomb.isSelected()) {
                db.modositBeszallito(beszallito);
            }
            if (torolRadioGomb.isSelected()) {
                db.torolBeszallito(beszallito);
            }
            beszallitoLista.setModel(new DefaultComboBoxModel(db.getBeszallitok()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hibás adatbevitel!");
        }

    }//GEN-LAST:event_hozzaadGombActionPerformed

    private void hozzaadRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadRadioGombActionPerformed
        nev.setEditable(true);
        nev.setBackground(Color.WHITE);
        telephely.setEditable(true);
        telephely.setBackground(Color.WHITE);
        telefonszam.setEditable(true);
        telefonszam.setBackground(Color.WHITE);
        email.setEditable(true);
        email.setBackground(Color.WHITE);
        adoszam.setEditable(true);
        adoszam.setBackground(Color.WHITE);
        beszallitoLista.setEnabled(false);
    }//GEN-LAST:event_hozzaadRadioGombActionPerformed

    private void modositRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modositRadioGombActionPerformed
        nev.setEditable(true);
        nev.setBackground(Color.WHITE);
        telephely.setEditable(true);
        telephely.setBackground(Color.WHITE);
        telefonszam.setEditable(true);
        telefonszam.setBackground(Color.WHITE);
        email.setEditable(true);
        email.setBackground(Color.WHITE);
        adoszam.setEditable(true);
        adoszam.setBackground(Color.WHITE);
        beszallitoLista.setEnabled(true);
    }//GEN-LAST:event_modositRadioGombActionPerformed

    private void torolRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torolRadioGombActionPerformed
        nev.setEditable(false);
        nev.setBackground(Color.LIGHT_GRAY);
        telephely.setEditable(false);
        telephely.setBackground(Color.LIGHT_GRAY);
        telefonszam.setEditable(false);
        telefonszam.setBackground(Color.LIGHT_GRAY);
        email.setEditable(false);
        email.setBackground(Color.LIGHT_GRAY);
        adoszam.setEditable(false);
        adoszam.setBackground(Color.LIGHT_GRAY);
        beszallitoLista.setEnabled(true);
    }//GEN-LAST:event_torolRadioGombActionPerformed

    private void keresGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keresGombActionPerformed
        if (modositRadioGomb.isSelected()) {
            try {
                Beszállító beszallito = (Beszállító) beszallitoLista.getSelectedItem();
                nev.setText(beszallito.getCegNev());
                telephely.setText(beszallito.getTelephely());
                email.setText(beszallito.getCegEmailCim());
                adoszam.setText(beszallito.getCegAdoSzam());
                telefonszam.setText(beszallito.getCegTelefonSzam());

                nev.setEditable(true);
                nev.setBackground(Color.WHITE);
                telephely.setEditable(true);
                telephely.setBackground(Color.WHITE);
                telefonszam.setEditable(true);
                telefonszam.setBackground(Color.WHITE);
                email.setEditable(true);
                email.setBackground(Color.WHITE);
                adoszam.setEditable(true);
                adoszam.setBackground(Color.WHITE);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nincs ilyen beszállító!");
            }
        }
        if (torolRadioGomb.isSelected()) {
            try {
                Beszállító beszallito = (Beszállító) beszallitoLista.getSelectedItem();
                nev.setText(beszallito.getCegNev());
                telephely.setText(beszallito.getTelephely());
                email.setText(beszallito.getCegEmailCim());
                adoszam.setText(beszallito.getCegAdoSzam());
                telefonszam.setText(beszallito.getCegTelefonSzam());

                nev.setEditable(false);
                nev.setBackground(Color.LIGHT_GRAY);
                telephely.setEditable(false);
                telephely.setBackground(Color.LIGHT_GRAY);
                telefonszam.setEditable(false);
                telefonszam.setBackground(Color.LIGHT_GRAY);
                email.setEditable(false);
                email.setBackground(Color.LIGHT_GRAY);
                adoszam.setEditable(false);
                adoszam.setBackground(Color.LIGHT_GRAY);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nincs ilyen beszállító!");
            }
        }
    }//GEN-LAST:event_keresGombActionPerformed
    public JComboBox getBeszallitoComboBox() {
        return this.beszallitoLista;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adoszam;
    private javax.swing.JComboBox beszallitoLista;
    private javax.swing.JTextField email;
    private javax.swing.JButton hozzaadGomb;
    private javax.swing.JRadioButton hozzaadRadioGomb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton keresGomb;
    private javax.swing.JRadioButton modositRadioGomb;
    private javax.swing.JTextField nev;
    private javax.swing.ButtonGroup radioGombok;
    private javax.swing.JTextField telefonszam;
    private javax.swing.JTextField telephely;
    private javax.swing.JRadioButton torolRadioGomb;
    // End of variables declaration//GEN-END:variables
}
