
import java.awt.Color;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.JTextComponent;
import newpackage.Beszállító;
import newpackage.DbKapcsolat;
import newpackage.Termék;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kicsi
 */
public class TermekHozzaad extends javax.swing.JPanel {

    private DbKapcsolat db;

    public TermekHozzaad() {
        db = frame.getDbKapcsolat();
        initComponents();
        radioGombok.add(hozzaadRadioGomb);
        radioGombok.add(modositRadioGomb);
        radioGombok.add(torolRadioGomb);

        cikkszam.setEditable(false);
        cikkszam.setBackground(Color.LIGHT_GRAY);
        megnevezes.setEditable(false);
        megnevezes.setBackground(Color.LIGHT_GRAY);
        ar.setEditable(false);
        ar.setBackground(Color.LIGHT_GRAY);
        beszallitoLista.setEnabled(false);
        AutoCompleteDecorator.decorate(beszallitoLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGombok = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        hozzaadRadioGomb = new javax.swing.JRadioButton();
        modositRadioGomb = new javax.swing.JRadioButton();
        torolRadioGomb = new javax.swing.JRadioButton();
        beszallitoLista = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cikkszam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        megnevezes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ujTermekHozzaad = new javax.swing.JButton();
        termekKerekGomb = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Termék műveletek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Beszállító megnevezés:");

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        hozzaadRadioGomb.setBackground(new java.awt.Color(0, 102, 153));
        hozzaadRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hozzaadRadioGomb.setForeground(new java.awt.Color(255, 255, 255));
        hozzaadRadioGomb.setText("Új termék hozzáadása");
        hozzaadRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadRadioGombActionPerformed(evt);
            }
        });

        modositRadioGomb.setBackground(new java.awt.Color(0, 102, 153));
        modositRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modositRadioGomb.setForeground(new java.awt.Color(255, 255, 255));
        modositRadioGomb.setText("Termék adatmódosítás");
        modositRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modositRadioGombActionPerformed(evt);
            }
        });

        torolRadioGomb.setBackground(new java.awt.Color(0, 102, 153));
        torolRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        torolRadioGomb.setForeground(new java.awt.Color(255, 255, 255));
        torolRadioGomb.setText("Termék törlés");
        torolRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torolRadioGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(hozzaadRadioGomb)
                .addGap(82, 82, 82)
                .addComponent(modositRadioGomb)
                .addGap(89, 89, 89)
                .addComponent(torolRadioGomb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hozzaadRadioGomb)
                    .addComponent(modositRadioGomb)
                    .addComponent(torolRadioGomb))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        beszallitoLista.setEditable(true);
        beszallitoLista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cikkszám:");

        cikkszam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cikkszam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikkszamActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Megnevezés");

        megnevezes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ár:");

        ar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plane-512 (1).png"))); // NOI18N
        jButton1.setToolTipText("Új beszállító hozzáadása");
        jButton1.setBorderPainted(false);

        ujTermekHozzaad.setBackground(new java.awt.Color(0, 102, 153));
        ujTermekHozzaad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick-512 (1).png"))); // NOI18N
        ujTermekHozzaad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujTermekHozzaadActionPerformed(evt);
            }
        });

        termekKerekGomb.setText("jButton2");
        termekKerekGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termekKerekGombActionPerformed(evt);
            }
        });

        jLabel6.setText("legyen unique mert igy nemjo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cikkszam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(termekKerekGomb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(megnevezes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(385, 385, 385)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ujTermekHozzaad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(beszallitoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(601, 601, 601))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 112, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(megnevezes, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(ar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(ujTermekHozzaad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(499, 499, 499))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(beszallitoLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cikkszam, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(termekKerekGomb)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox getBeszallitoComboBox() {
        return this.beszallitoLista;
    }

    private void cikkszamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikkszamActionPerformed

    }//GEN-LAST:event_cikkszamActionPerformed

    private void ujTermekHozzaadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujTermekHozzaadActionPerformed
        try {
            int cegId_ = ((Beszállító) beszallitoLista.getSelectedItem()).getCegId();
            String cikkszam_ = cikkszam.getText();
            String megnevezes_ = megnevezes.getText();
            int ar_ = Integer.parseInt(ar.getText());

            if (cikkszam_.equals("") || megnevezes_.equals("") || ar.getText() == "") {
                JOptionPane.showMessageDialog(null, "Az adatok megadása kötelező!");
                return;
            }
            Termék termek = new Termék(cegId_, cikkszam_, megnevezes_, ar_);

            if (hozzaadRadioGomb.isSelected()) {
                db.ujTermek(termek);
            }
            if (modositRadioGomb.isSelected()) {
                db.modositTermek(termek);
            }
            if (torolRadioGomb.isSelected()) {
                db.torolTermek(termek);
            }
            cikkszam.setText("");
            megnevezes.setText("");
            ar.setText("");
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Az adatok megadása kötelező!"); 
        }


    }//GEN-LAST:event_ujTermekHozzaadActionPerformed

    private void hozzaadRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadRadioGombActionPerformed
        cikkszam.setEditable(true);
        cikkszam.setBackground(Color.WHITE);
        megnevezes.setEditable(true);
        megnevezes.setBackground(Color.WHITE);
        ar.setEditable(true);
        ar.setBackground(Color.WHITE);
        beszallitoLista.setEnabled(true);
    }//GEN-LAST:event_hozzaadRadioGombActionPerformed

    private void modositRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modositRadioGombActionPerformed
        cikkszam.setEditable(true);
        cikkszam.setBackground(Color.WHITE);
        megnevezes.setEditable(false);
        megnevezes.setBackground(Color.LIGHT_GRAY);
        ar.setEditable(false);
        ar.setBackground(Color.LIGHT_GRAY);
        beszallitoLista.setEnabled(false);


    }//GEN-LAST:event_modositRadioGombActionPerformed

    private void termekKerekGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termekKerekGombActionPerformed
        if (modositRadioGomb.isSelected()) {
            try {

                Termék termek = db.lekerdezTermek(cikkszam.getText());
                int cegId = termek.getBeszallitoId();
                megnevezes.setText(termek.getMegnevezes());
                ar.setText(String.valueOf(termek.getAr()));
                megnevezes.setEditable(true);
                megnevezes.setBackground(Color.WHITE);
                ar.setEditable(true);
                ar.setBackground(Color.WHITE);
                beszallitoLista.setEnabled(true);
                beszallitoLista.setSelectedItem(db.lekerdezBeszallito(cegId));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nincs ilyen termék!");
            }
        }
        if (torolRadioGomb.isSelected()) {
            try {
                Termék termek = db.lekerdezTermek(cikkszam.getText());
                int cegId = termek.getBeszallitoId();
                megnevezes.setText(termek.getMegnevezes());
                ar.setText(String.valueOf(termek.getAr()));
                beszallitoLista.setSelectedItem(db.lekerdezBeszallito(cegId));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nincs ilyen termék!");
            }
        }
    }//GEN-LAST:event_termekKerekGombActionPerformed

    private void torolRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torolRadioGombActionPerformed
        cikkszam.setEditable(true);
        cikkszam.setBackground(Color.WHITE);
        megnevezes.setEditable(false);
        megnevezes.setBackground(Color.LIGHT_GRAY);
        ar.setEditable(false);
        ar.setBackground(Color.LIGHT_GRAY);
        beszallitoLista.setEnabled(false);
    }//GEN-LAST:event_torolRadioGombActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ar;
    private javax.swing.JComboBox beszallitoLista;
    private javax.swing.JTextField cikkszam;
    private javax.swing.JRadioButton hozzaadRadioGomb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField megnevezes;
    private javax.swing.JRadioButton modositRadioGomb;
    private javax.swing.ButtonGroup radioGombok;
    private javax.swing.JButton termekKerekGomb;
    private javax.swing.JRadioButton torolRadioGomb;
    private javax.swing.JButton ujTermekHozzaad;
    // End of variables declaration//GEN-END:variables
}
