
import java.awt.Color;
import javax.swing.JOptionPane;
import newpackage.DbKapcsolat;
import newpackage.Vevő;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kicsi
 */
public class VevoHozzaad extends javax.swing.JPanel {

    private DbKapcsolat db;

    public VevoHozzaad() {
        initComponents();
        radioGombok.add(hozzaadRadioGomb);
        radioGombok.add(modositRadioGomb);
        radioGombok.add(torolRadioGomb);
        db = frame.getDbKapcsolat();

        keresztNev.setEditable(false);
        keresztNev.setBackground(Color.LIGHT_GRAY);
        vezetekNev.setEditable(false);
        vezetekNev.setBackground(Color.LIGHT_GRAY);
        cim.setEditable(false);
        cim.setBackground(Color.LIGHT_GRAY);
        telefonszam.setEditable(false);
        telefonszam.setBackground(Color.LIGHT_GRAY);
        email.setEditable(false);
        email.setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGombok = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hozzaad = new javax.swing.JButton();
        vezetekNev = new javax.swing.JTextField();
        telefonszam = new javax.swing.JTextField();
        keresztNev = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        cim = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        hozzaadRadioGomb = new javax.swing.JRadioButton();
        modositRadioGomb = new javax.swing.JRadioButton();
        torolRadioGomb = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        vasarloLista = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vezetéknév:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefonszám:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Keresztnév:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-mail cím:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cím:");

        hozzaad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick-512 (1).png"))); // NOI18N
        hozzaad.setBorderPainted(false);
        hozzaad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadActionPerformed(evt);
            }
        });

        vezetekNev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        telefonszam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        keresztNev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        cim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Vásárló műveletek");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        hozzaadRadioGomb.setBackground(new java.awt.Color(0, 102, 153));
        hozzaadRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hozzaadRadioGomb.setForeground(new java.awt.Color(255, 255, 255));
        hozzaadRadioGomb.setText("Új vásárló hozzáadása");
        hozzaadRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hozzaadRadioGombActionPerformed(evt);
            }
        });

        modositRadioGomb.setBackground(new java.awt.Color(0, 102, 153));
        modositRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        modositRadioGomb.setForeground(new java.awt.Color(255, 255, 255));
        modositRadioGomb.setText("Vásárló adatmódosítás");
        modositRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modositRadioGombActionPerformed(evt);
            }
        });

        torolRadioGomb.setBackground(new java.awt.Color(0, 102, 153));
        torolRadioGomb.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        torolRadioGomb.setForeground(new java.awt.Color(255, 255, 255));
        torolRadioGomb.setText("Vásárló törlés");
        torolRadioGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torolRadioGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(hozzaadRadioGomb)
                .addGap(85, 85, 85)
                .addComponent(modositRadioGomb)
                .addGap(100, 100, 100)
                .addComponent(torolRadioGomb)
                .addContainerGap(604, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hozzaadRadioGomb)
                    .addComponent(modositRadioGomb)
                    .addComponent(torolRadioGomb))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vásárló kiválasztása:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(1127, 1127, 1127)
                        .addComponent(hozzaad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vasarloLista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vezetekNev)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cim)
                                            .addComponent(keresztNev, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(107, 107, 107)
                                        .addComponent(jLabel2)
                                        .addGap(43, 43, 43)
                                        .addComponent(telefonszam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vasarloLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vezetekNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(keresztNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(telefonszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hozzaad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hozzaadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadActionPerformed

        try {
            String keresztNev_ = keresztNev.getText();

            String vezetekNev_ = vezetekNev.getText();
            String cim_ = cim.getText();
            String telefonSzam_ = telefonszam.getText();
            String email_ = email.getText();

            if (keresztNev_.equals("") || vezetekNev_.equals("") || email_.equals("") || cim_.equals("")) {
                JOptionPane.showMessageDialog(null, "A vezetéknév, keresztnév, cím, e-mail cím megadása kötelező!");
                return;
            }
            if (!(email_.contains("@") && email_.contains("."))) {
                JOptionPane.showMessageDialog(null, "Hibás e-mail cím!");
                return;
            }

            Vevő vevo = new Vevő(vezetekNev_, keresztNev_, cim_, telefonSzam_, email_);
            if (hozzaadRadioGomb.isSelected()) {
                db.ujVevo(vevo);
            }
            if (modositRadioGomb.isSelected()) {
                db.modositVevo(vevo);
            }
            if (torolRadioGomb.isSelected()) {
                db.torolVevo(vevo);
            }
            vezetekNev.setText("");
            keresztNev.setText("");
            telefonszam.setText("");
            email.setText("");
            cim.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hibás adatbevitel!");
        }

    }//GEN-LAST:event_hozzaadActionPerformed

    private void hozzaadRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hozzaadRadioGombActionPerformed
        keresztNev.setEditable(true);
        keresztNev.setBackground(Color.WHITE);
        vezetekNev.setEditable(true);
        vezetekNev.setBackground(Color.WHITE);
        cim.setEditable(true);
        cim.setBackground(Color.WHITE);
        telefonszam.setEditable(true);
        telefonszam.setBackground(Color.WHITE);
        email.setEditable(true);
        email.setBackground(Color.WHITE);
    }//GEN-LAST:event_hozzaadRadioGombActionPerformed

    private void modositRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modositRadioGombActionPerformed
        keresztNev.setEditable(false);
        keresztNev.setBackground(Color.LIGHT_GRAY);
        vezetekNev.setEditable(false);
        vezetekNev.setBackground(Color.LIGHT_GRAY);
        cim.setEditable(false);
        cim.setBackground(Color.LIGHT_GRAY);
        telefonszam.setEditable(false);
        telefonszam.setBackground(Color.LIGHT_GRAY);
        email.setEditable(true);
        email.setBackground(Color.WHITE);
    }//GEN-LAST:event_modositRadioGombActionPerformed

    private void torolRadioGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torolRadioGombActionPerformed
        keresztNev.setEditable(false);
        keresztNev.setBackground(Color.LIGHT_GRAY);
        vezetekNev.setEditable(false);
        vezetekNev.setBackground(Color.LIGHT_GRAY);
        cim.setEditable(false);
        cim.setBackground(Color.LIGHT_GRAY);
        telefonszam.setEditable(false);
        telefonszam.setBackground(Color.LIGHT_GRAY);
        email.setEditable(true);
        email.setBackground(Color.WHITE);
    }//GEN-LAST:event_torolRadioGombActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (modositRadioGomb.isSelected()) {
            try {

                Vevő vevo = db.lekerdezVevo(email.getText());
                vezetekNev.setText(vevo.getVezetekNev());
                keresztNev.setText(vevo.getKeresztNev());
                cim.setText(vevo.getVevoCim());
                telefonszam.setText(vevo.getVevoTelefonSzam());

                keresztNev.setEditable(true);
                keresztNev.setBackground(Color.WHITE);
                vezetekNev.setEditable(true);
                vezetekNev.setBackground(Color.WHITE);
                cim.setEditable(true);
                cim.setBackground(Color.WHITE);
                telefonszam.setEditable(true);
                telefonszam.setBackground(Color.WHITE);
                email.setEditable(true);
                email.setBackground(Color.WHITE);
            } catch (Exception e) {
            }
        }
        if (torolRadioGomb.isSelected()) {
            try {
                Vevő vevo = db.lekerdezVevo(email.getText());
                vezetekNev.setText(vevo.getVezetekNev());
                keresztNev.setText(vevo.getKeresztNev());
                cim.setText(vevo.getVevoCim());
                telefonszam.setText(vevo.getVevoTelefonSzam());

                keresztNev.setEditable(false);
                keresztNev.setBackground(Color.LIGHT_GRAY);
                vezetekNev.setEditable(false);
                vezetekNev.setBackground(Color.LIGHT_GRAY);
                cim.setEditable(false);
                cim.setBackground(Color.LIGHT_GRAY);
                telefonszam.setEditable(false);
                telefonszam.setBackground(Color.LIGHT_GRAY);
                email.setEditable(true);
                email.setBackground(Color.WHITE);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cim;
    private javax.swing.JTextField email;
    private javax.swing.JButton hozzaad;
    private javax.swing.JRadioButton hozzaadRadioGomb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField keresztNev;
    private javax.swing.JRadioButton modositRadioGomb;
    private javax.swing.ButtonGroup radioGombok;
    private javax.swing.JTextField telefonszam;
    private javax.swing.JRadioButton torolRadioGomb;
    private javax.swing.JComboBox vasarloLista;
    private javax.swing.JTextField vezetekNev;
    // End of variables declaration//GEN-END:variables
}
